### ISSUE TITLE
[BUG] Stone tools

### ISSUE THREAD

**Issue by K0rS1z** [diskree/AchieveToDo#1]
Somehow managed to circumvent the restriction on the use of stone tools. The only thing I did was craft them all at once. I apologize in advance if this does not help to repeat the bug, because I found out about it by accident. Thanks!
![2023-08-16_14 39 30](https://github.com/diskree/AchieveToDo/assets/142387212/31835887-8f9d-4e16-b3bf-9acd2c7e68ec)
![2023-08-16_14 39 34](https://github.com/diskree/AchieveToDo/assets/142387212/be43891a-463f-4bf1-8332-25d100444135)

**Comment by K0rS1z** [comment]
Perhaps you don't need 110 achievements there, because you also need 110 to open iron tools...

**Comment by diskree** [comment]
Yes, this is my mistake, which has already been fixed and will be included in the next update. Stone tools should actually require 70 achievements
